'use client';
import {useEffect,useState} from 'react';

type Tone={id:number;title?:string;models_count?:number}; type Model={id:number;name?:string};
type Hid={vendorId:number;productName?:string;opened:boolean;open:()=>Promise<void>;sendReport:(id:number,data:BufferSource)=>Promise<void>;addEventListener:(n:string,h:(e:Event)=>void)=>void;removeEventListener:(n:string,h:(e:Event)=>void)=>void};
type HidApi={getDevices:()=>Promise<Hid[]>;requestDevice:(o:{filters:{vendorId:number}[]})=>Promise<Hid[]>};

export default function ToneHidManager(){
 const [tones,setTones]=useState<Tone[]>([]),[models,setModels]=useState<Model[]>([]),[selected,setSelected]=useState<Tone|null>(null),[device,setDevice]=useState<Hid|null>(null),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[file,setFile]=useState<File|null>(null);
 const hid=()=> (navigator as Navigator&{hid?:HidApi}).hid;
 async function refresh(){const h=hid();if(h)setDevice((await h.getDevices()).find(d=>d.vendorId===0xcafe)||null)}
 async function connect(){const h=hid();if(!h)return setStatus('当前浏览器不支持 WebHID，请使用 Chrome 或 Edge');try{const ds=await h.requestDevice({filters:[{vendorId:0xcafe}]});const d=ds[0];if(!d.opened)await d.open();setDevice(d);setStatus('Pico NAM 已连接（WebHID）')}catch(e){if((e as Error).name!=='NotFoundError')setStatus('连接 Pico NAM 失败')}}
 async function search(){const r=await fetch(`/api/tone3000/search?query=${encodeURIComponent(query)}`),d=await r.json();if(!r.ok)throw Error(d.error||'搜索失败');setTones(d.data||[])}
 async function choose(t:Tone){setSelected(t);const r=await fetch(`/api/tone3000/models?tone_id=${t.id}`),d=await r.json();if(!r.ok)throw Error(d.error||'获取模型失败');setModels(d.data||[])}
 async function send(root:unknown,label:string){if(!device)throw Error('请先连接 Pico NAM');const x=root as {architecture?:string;config?:{submodels?:{model?:unknown}[]};weights?:number[]};const cs=x.architecture==='SlimmableContainer'?(x.config?.submodels||[]).map(s=>s.model).filter(Boolean):[x];const m=(cs.find(v=>(v as {config?:{layers?:{channels?:number}[]}}).config?.layers?.[0]?.channels===3)||cs[0]) as {weights?:number[]};if(!Array.isArray(m?.weights))throw Error('没有可用的 A2 权重');const p=new Float32Array(m.weights),raw=new Uint8Array(p.buffer),all=new Uint8Array(16+raw.length);all.set([78,65,77,87]);new DataView(all.buffer).setUint32(4,1,true);new DataView(all.buffer).setUint32(8,p.length,true);new DataView(all.buffer).setUint32(12,raw.length,true);all.set(raw,16);for(let o=0;o<all.length;o+=63){const report=new Uint8Array(64);report.set(all.slice(o,o+63));await device.sendReport(0,report);setStatus(`正在导入 ${label}：${Math.min(100,Math.round((o/all.length)*100))}%`)}setStatus(`已导入：${label}`)}
 async function local(){if(!file)return;try{await send(JSON.parse(await file.text()),file.name)}catch(e){setStatus(e instanceof Error?e.message:'导入失败')}}
 async function direct(m:Model){try{setStatus('正在下载并导入…');const r=await fetch(`/api/tone3000/model/${m.id}`);await send(JSON.parse(await r.text()),m.name||`NAM ${m.id}`)}catch(e){setStatus(e instanceof Error?e.message:'导入失败')}}
 useEffect(()=>{search().catch(e=>setStatus(e.message));refresh().catch(()=>{});const h=hid();if(!h)return;const on=()=>refresh().catch(()=>{});h.getDevices().then(()=>{});return()=>{void on}},[]);
 return <main className="min-h-screen bg-[#0a0a0a] px-6 py-20 text-[#f5f5f5]"><div className="mx-auto max-w-4xl"><h1 className="text-4xl font-bold">NAM 音色管理</h1><p className="mt-4 text-white/60">USB 音频 + WebHID 动态 NAM 切换</p><div className="mt-6 flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-4"><span>{device?'🟢 设备已连接':'⚪ Pico NAM 未连接'}</span><button onClick={connect} className="rounded-full border border-[#e8a850] px-4 py-2 text-sm text-[#e8a850]">{device?'重新连接':'连接设备'}</button></div><div className="mt-8 flex gap-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索音色名称、品牌…" className="flex-1 rounded-full border border-white/15 bg-white/5 px-4 py-3"/><button onClick={()=>search().catch(e=>setStatus(e.message))} className="rounded-full bg-[#e8a850] px-6 py-3 font-bold text-black">搜索</button></div><div className="mt-6 grid gap-3 md:grid-cols-2">{tones.map(t=><button key={t.id} onClick={()=>choose(t).catch(e=>setStatus(e.message))} className="rounded-xl border border-white/10 bg-white/5 p-4 text-left">{t.title||`Tone ${t.id}`}<span className="mt-1 block text-xs text-white/50">ID {t.id} · A2 NAM</span></button>)}</div>{selected&&<section className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold">{selected.title}</h2><div className="mt-4 flex flex-wrap items-center gap-3 rounded-xl border border-dashed border-white/20 p-4"><label className="cursor-pointer rounded-full border border-white/30 px-4 py-2">选择本地 NAM<input type="file" accept=".nam,application/json" className="hidden" disabled={!device} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><span className="text-sm text-white/60">{file?.name||'未选择文件'}</span><button disabled={!device||!file} onClick={local} className="rounded-full bg-[#e8a850] px-4 py-2 font-bold text-black disabled:opacity-40">导入到 Pico</button></div><div className="mt-4 space-y-3">{models.map(m=><div key={m.id} className="flex items-center justify-between rounded-xl bg-black/30 p-4"><span>{m.name||`NAM ${m.id}`}</span><div className="flex gap-2"><a href={`/api/tone3000/model/${m.id}`} className="rounded-full border border-white/30 px-3 py-2 text-sm">下载</a><button disabled={!device} onClick={()=>direct(m)} className="rounded-full bg-[#e8a850] px-3 py-2 text-sm font-bold text-black disabled:opacity-40">下载并导入 Pico</button></div></div>)}</div></section>}{status&&<p className="mt-6 text-sm text-[#e8a850]">{status}</p>}</div></main>}
